[package]
name = "piratepaperlib"
version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
default = ["printpdf"]
printpdf = ["dep:printpdf", "dep:qrcode"]

[dependencies]
bech32 = "0.11"
bip39 = "2.1"
blake2b_simd = "1.0"
hex = "0.4"
orchard = { git = "https://github.com/PirateNetwork/orchard.git", rev = "c0545158b15259805e31ea1953867d6a507c08e4", default-features = false, features = ["std"] }
rand = "0.8"
rand_chacha = "0.3"
sapling = { package = "sapling-crypto", git = "https://github.com/piratenetwork/sapling-crypto.git", rev = "62fcf59a4d933244ee6280182c6cd3e5290e8a90", default-features = false, features = ["std"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
zip32 = "0.2.1"
printpdf = { version = "0.12.8", default-features = false, optional = true }
qrcode = { version = "0.14.1", default-features = false, optional = true }
